Cloud\UserBundle\Entity\Fitxer:
    type: entity
    table: null
    repositoryClass: Cloud\UserBundle\Entity\FitxerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        description:
            type: string
            length: 255
        modificacion:
            type: string
            length: 255
        idUser:
            type: integer
            column: id_user
        eliminado:
                    type: boolean
                    column: eliminado
        favorito:
                             type: string
                             column: favorito
    lifecycleCallbacks: {  }
