<?php

namespace Cloud\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FitxerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitxerRepository extends EntityRepository
{
}
